---
name: pose-publisher
services:
  core:
    image: pose-publisher:noetic-devel
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Base image to contruct current image
        image_base_version: 0.5.0
        ros_distro: noetic
        version: devel
