---
name: pose-publisher
services:
  core:
    image: pose-publisher:noetic-0.1.3-rc01
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Base image to contruct current image
        image_base_version: a07f857-20231115
        ros_distro: noetic
        version: 0.1.3-rc01
