---
name: pose-publisher
services:
  core:
    image: pose-publisher:noetic-devel
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        # Base image to contruct current image
        image_version: 0.2.1
