---
name: pose-publisher
services:
  core:
    image: pose-publisher:noetic-0.1.0-rc01
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        # Base image to contruct current image
        image_version: 0.2.1
