---
name: open-rmf
services:
  core:
    image: ${REGISTRY_BASE}/library/${IMAGE_NAME}:humble-${GITHUB_REF_NAME}
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        # Base image to contruct current image
        image_version: 0.2.1
