---
name: pose-publisher
services:
  core:
    image: pose-publisher:noetic-0.1.0-rc01
    environment:
      #  GEN_COMMAND: sleep infinity
      #  STARTUP_TYPE: generic
      ROBOT_ID: "robot"
      POSE_PUBLISHER_FREQUENCY: "10"
      POSE_PUBLISHER_BASE_FRAME_SUFFIX: "base_footprint"
      POSE_PUBLISHER_TOPIC_REPUB: "pose"
      MAP_FRAME: "robot_map"
